/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_corp_quanta_ndksample_MainActivity */

#ifndef _Included_com_corp_quanta_ndksample_MainActivity
#define _Included_com_corp_quanta_ndksample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_corp_quanta_ndksample_MainActivity
 * Method:    getStringFormNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_corp_quanta_ndksample_MainActivity_getStringFormNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
